# Generated by Django 4.1.7 on 2023-02-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_no_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
