# Generated by Django 4.1.7 on 2023-02-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_is_phone_no_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Roll',
            new_name='roll',
        ),
    ]
