# Generated by Django 4.1.7 on 2023-02-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_roll_studentmodel_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_phone_no_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=9827052717),
            preserve_default=False,
        ),
    ]
